import { model } from "@medusajs/framework/utils"

export const Carmodel = model.define("carmodel", {
  id: model.id().primaryKey(),
  name: model.text(),
  title: model.text().nullable(),
  intro: model.text().nullable(),
  description: model.text().nullable(),
  image: model.text().nullable(),

  PictureId:model.text().nullable(),
  Description:model.text().nullable(),
  MetaKeywords:model.text().nullable(),
  MetaDescription:model.text().nullable(),
  MetaTitle:model.text().nullable(),
  Published: model.number().nullable(),
  Deleted: model.boolean().nullable(),
  DisplayOrder: model.number().nullable(),
  CreatedOnUtc: model.dateTime().nullable(),
  UpdatedOnUtc: model.dateTime().nullable(),
  ModelBannerId:model.text().nullable(),
  ChargingStationDescription:model.text().nullable(),
  ChargingCableDescription:model.text().nullable(),
  AccessoriesDescription:model.text().nullable(),
  ModelBannerDescription:model.text().nullable(),
  CableType:model.number().nullable(),
  is1F16A:model.number().nullable(),
  is1F32A:model.number().nullable(),
  is3F16A:model.number().nullable(),
  is3F32A:model.number().nullable(),
  CablePictureId:model.number().nullable(),
  StructuredData:model.text().nullable(),
  H1Title:model.text().nullable(),
})